# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s-vuJnqMB1t4sL0WoLR43bvAxrWtfT4
"""

!pip install transformers
!pip install gradio

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

model_name = "gpt2-medium"  # More balanced than small GPT-2
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

def generate_response(user_input):
    prompt = (
        "You are MindMender, a kind and helpful AI psychologist. "
        "You offer calm, empathetic responses to help users manage stress, anxiety, or loneliness. "
        "You also suggest journaling prompts, breathing exercises, or CBT-style questions.\n\n"
        f"User: {user_input}\nMindMender:"
    )

    input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)

    output = model.generate(
        input_ids,
        max_length=200,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.7,
        pad_token_id=tokenizer.eos_token_id
    )

    response = tokenizer.decode(output[0], skip_special_tokens=True)
    return response.split("MindMender:")[-1].strip()

import gradio as gr

gr.Interface(
    fn=generate_response,
    inputs=gr.Textbox(lines=5, placeholder="Tell me what's on your mind..."),
    outputs="text",
    title="🧠 MindMender - AI Psychology Chatbot",
    description="Talk to MindMender about your thoughts. It offers emotional support, journaling prompts, and gentle CBT-style help."
).launch()